collaborative/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

from collaborative import views


urlpatterns = [
    url(r'^$', views.root),
    url('', include('social_django.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication & Redirection to Wizard URLs
    path('admin/', admin.site.urls),
    path('request-access/', views.request_access, name='request-access'),
    path('setup-check/', views.redirect_wizard_or_admin, name='setup-check'),

    # DB Schema & CSV Importing Endpoints (can be used to edit, too)
    path('db-config/',
         include('django_models_from_csv.urls', namespace="db-config")),

    # Setup password and OAuth
    path('setup-credentials/',
         views.setup_credentials, name='setup-credentials'),
    # Success page
    path('setup-complete/', views.setup_complete, name='setup-complete'),
]

django_models_from_csv/urls.py
from django.conf.urls import url
from django.urls import path

from django_models_from_csv import views


app_name = "csv_models"

urlpatterns = [
    # Create a new sheet table (enters wizard)
    path('begin/', views.begin, name='begin'),
    # Build the database table from the sheet
    path('refine-and-import/<int:id>/', views.refine_and_import,
         name='refine-and-import'),
    path('refine-and-import/<str:name>/', views.refine_and_import_by_name,
         name='refine-and-import'),

    # endpoint for autocompleting tags
    url(r'^tag-autocomplete/$', views.TagAutocomplete.as_view(),
        name='tag-autocomplete'),

    # Admin list view field updater
    path('object-updater/', views.field_updater, name='object-updater'),
]

templates/begin-setup.html
{% extends "setup-base.html" %}
{% load i18n static %}

{% block title %}
System Setup | {{ block.super }}
{% endblock %}

{% block content %}
  <h2>System Setup</h2>
  <form>
    <div class="base-config">
      {% trans 'Google Sheet URL' as sheets_label %}
      <label for="sheets_url">{{ sheets_label }}</label>
      <input name="sheets_url" type="text" placeholder="e.g., https://docs.google.com/spreadsheets/d/1w2Bt..." required />
    </div>

    <div class="authentication">
      <h3>Google Sign In</h3>
      <p class="instructions">
        {% blocktrans trimmed %}
        In order to allow users to sign in with their Google account, you need
        to request access from Google to do this. Specifically, you need
        something called OAuth2 keys from Google. To get these keys, follow
        these steps:
        <ol>
          <li>
            Go to the <a href="https://console.developers.google.com/" target="_blank">Google Developer's Console</a>.
          </li>
          <li>
            Create a new project.
          </li>
          <li>
            On the left, select "Credentials"
          </li>
          <li>
            Select the "OAuth consent screen"
          </li>
          <li>
            Give your application a name and support email. Click "Save" at the
            bottom.
          </li>
          <li>
            Go back to the "Credentials" tab. Click "Create credentials" &rarr;
            "OAuth client ID".
          </li>
          <li>
            Select "Web application". This will expose more options.
          </li>
          <li>
            Under "Authorized JavaScript origins" enter:
            <code>http://localhost/</code><br/>
            Under "Authorized redirect URIs" enter:
            <code>http://localhost/complete/google-oauth2/</code><br/>
            Click "Save".
          </li>
          <li>
            This will bring up a prompt containing the Google
            OAuth2 Key and Secret. Copy each to the below input boxes.
          </li>
        </ol>
        {% endblocktrans %}
      </p>
      <div>
        <p>
          {% trans 'Google OAuth2 Key' as google_oauth_key %}
          <label for="google_oauth_key">{{ google_oauth_key }}</label>
          <input name="google_oauth_key" type="text" placeholder="long code, e.g., 327832290-ajn..." />
        </p>

        <p>
          {% trans 'Google OAuth2 Secret' as google_oauth_secret %}
          <label for="google_oauth_secret">{{ google_oauth_secret }}</label>
          <input name="google_oauth_secret" type="text" placeholder="short code, e.g., a708absY_s..." />
        </p>
      </div>
    </div>
    <div>
      <input type="submit" value="{% trans 'Continue' %}" />
    </div>
  </form>
{% endblock %}

templates/request-access.html
{% extends "django_models_from_csv/base.html" %}
{% load i18n static %}

{% block title %}
Access Denied | {{ block.super }}
{% endblock %}

{% block content %}
  <h2>Access Denied</h2>
  <div>
      <p>
      In order to access this system, you need an admin to create
      an account for you. When using a third party sign in, this
      account needs to match the email registered with the third
      party.
      </p>
      <p>
      You can resume the login process in the future using this
      link:
      </p>
      <p class="resume-link">
          <a href="{{ resume_url }}">{{ resume_url }}</a>
      </p>
{% endblock %}

templates/setup-begin.html
{% extends "setup-base.html" %}
{% load i18n static %}

{% block title %}
System Setup | {{ block.super }}
{% endblock %}

{% block content %}
<h2>System Setup</h2>
<form action="{% url 'db-config:begin' %}" method="POST">
    <div class="base-config">
        {% trans 'Google Sheet URL' as sheets_label %}
        <label for="csv_url">{{ sheets_label }}</label>
        <input name="csv_url" type="text" placeholder="e.g., https://docs.google.com/spreadsheets/d/1w2Bt..." required />
    </div>
    <div>
        {% trans 'Label this spreadsheet' as name_label %}
        <label for="name">{{ name_label }}</label>
        <input name="name" type="text" placeholder="Enter name..." required />
    </div>
    <div class="continue">
        <input type="submit" value="{% trans 'Continue' %}" />
    </div>
    {% csrf_token %}
</form>
{% endblock %}

templates/setup-complete.html
{% extends "django_models_from_csv/base.html" %}
{% load i18n static %}

{% block title %}
Success! | {{ block.super }}
{% endblock %}

{% block content %}
<div id="csv-models-config">
  <h2>Success!</h2>
  <p>
  {% blocktrans trimmed %}
  Congratulations, you've successfully configured Collaborate. Clicking
  below will complete the process, bringing you the login screen.
  </p>
  <p>
  From there, you can manage your imported data and add users. Good luck!
  </p>
  {% endblocktrans %}
  <p class="click-to-login">
    <a href="{% url 'admin:index' %}">Click here to log in.</a>
  </p>
</div>
{% endblock %}

templates/setup-import.html
{% extends "setup-base.html" %}
{% load i18n static %}

{% block title %}
Import Data | {{ block.super }}
{% endblock %}

{% block extrahead %}
<script type="text/javascript">
const done = () => {
  document.getElementById("continue").click();
};
setTimeout(done, 2500);
</script>
{% endblock %}

{% block content %}
<h2>Import Data</h2>
<form action="{% url 'csv_models:import-data' sheet.id %}" method="POST">
    {% if not errors %}
    <p>
    {% blocktrans trimmed %}
        We are about to import responses from the sheet into the system.
        You will be redirected shortly.
    {% endblocktrans %}
    </p>
    {% else %}
    <h3>Import Errors</h3>
    <p>
    {% blocktrans trimmed %}
        The following errors were encountered while importing the sheet.
        To fix these errors, you can either correct the problems in
        your sheet or you can go back and
        <a href="/setup-refine-schema">change the column types</a>.
    {% endblocktrans %}
    </p>
    {% for pk, errs in errors %}
        <p>
            <b>Row {{ pk }}:</b><br/>
            {% for e in errs %}
                {{ e.error.args  }}<br/>
            {% endfor %}
        </p>
    {% endfor %}
    {% endif %}
    <div class="continue">
        <input id="continue" type="submit" value="{% trans 'Continue' %}" />
    </div>
    {% csrf_token %}
</form>
{% endblock %}

templates/setup-refine-schema.html
{% extends "setup-base.html" %}
{% load i18n static %}

{% block title %}
Database Columns | {{ block.super }}
{% endblock %}

{% block content %}
<h2>Refine Database</h2>
<form action="{% url 'csv_models:refine-schema' sheet.id %}" method="POST">
    {% if not errors %}
    <p>
    {% blocktrans trimmed %}
        These are the column names and types we found in
        your sheet. Feel free to double check and correct
        any mistakes before continuing.
    {% endblocktrans %}
    {{ form }}
    </p>
    {% else %}
    <h3>Import Errors</h3>
    {% for pk, errs in errors %}
        <p>
            <b>Row {{ pk }}:</b><br/>
            {% for e in errs %}
                {{ e.error.args  }}<br/>
            {% endfor %}
        </p>
    {% endfor %}
    {% endif %}
    <div class="continue">
        <input type="submit" value="{% trans "Continue" %}" />
    </div>
    {% csrf_token %}
</form>
{% endblock %}

templates/setup-wait.html
{% extends "setup-base.html" %}
{% load i18n static %}

{% block title %}
Redirecting | {{ block.super }}
{% endblock %}

{% block extrahead %}
<script type="text/javascript">
let interval = null;
const httpGet = (url, cb) => {
  const xmlHttp = new XMLHttpRequest();
  xmlHttp.onreadystatechange = function() {
    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
      cb(xmlHttp.responseText);
  }
  xmlHttp.open("GET", url, true);
  xmlHttp.send(null);
};
const httpPost = (url, token, cb) => {
  const xmlHttp = new XMLHttpRequest();
  xmlHttp.onreadystatechange = function() {
    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
      cb(xmlHttp.responseText);
  }
  xmlHttp.open("POST", url, true);
  xmlHttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  xmlHttp.send(`token=${token}`);
};
const done = () => {
  clearInterval(interval);
  document.getElementById("nextPage").click();
};
const check = () => {
  const urlParams = new URLSearchParams(window.location.search);
  const next = urlParams.get('next');
  httpGet(next, done);
};
const startWait = () => {
  interval = setInterval(check, 500);
};
const triggerMigrations = () => {
  const urlParams = new URLSearchParams(window.location.search);
  const token = urlParams.get('token');
  httpPost("{% url 'csv_models:migrate' %}", token, startWait);
};
setTimeout(triggerMigrations, 2000);
</script>
{% endblock %}

{% block content %}
<h2>{% trans "System is loading, please wait..." %}</h2>
<p>
{% blocktrans trimmed %}
You will be redirected once this is complete.
If you are not redirected shortly, please <a id="nextPage" href="{{ next }}">click here</a>.
{% endblocktrans %}
</p>
{% endblock %}